### ISSUE TITLE
Sorted Array

### ISSUE THREAD

**Issue by vinibalbino** [giacomoquinalia/binarySearch#1]
**Hello Giacomo**
How are you?

One thing you have to remind that the binary search only works if the array is sorted!

You can use the sort method, to sort the array, down bellow a example
``` javascript
var array = [ 4, 2, 5, 1, 3 ]
array.sort( function(a,b) {
    return a - b;
});
console.log(array);

// expected output: Array [1, 2, 3, 4, 5]
```

**Comment by giacomoquinalia** [comment]
Opa, tranquilo?
Fiz o código pensando somente em dar a resposta com os parâmetros corretos, sobre a entrada dos dados e o tratamento de erro deixei por conta do programador verificar. Caso o array esteja desordenado a resposta é "-1" para indicar erro.
Vou adicionar isso ao README para deixar explícito. Valeu pelo toque!

**Comment by vinibalbino** [comment]
Denada!
